name: CI/CD Deploy Infra 🚀

on:
  workflow_dispatch:

jobs:
  ci-feature:
    uses: jhegner/kubernetes-labs-ci-workflows/.github/workflows/2-reusable-deploy-infra.yml@main
    secrets:
      VULTR_API_KEY: ${{ secrets.VULTR_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
